### PR TITLE
Basic features for voters

### PR DESCRIPTION
**Pull request by graphiclunarkid**
This branch implements a first-cut feature for voters to look up what their candidates have said.
- YNMP postcode-to-constituency lookup
- Constituencies are saved in the database if not already present
- Constituency URLs exist
- Candidate, organisation, question and answer data displayed on constituency pages
- Unit and functional tests written and passing

To-do
- Unit tests for YNMP constituency-from-postcode lookup (mocking urlopen)
- Refactor Candidates to make constituency_id a FK to the Constituency table
- Order the data on the constituency page like: Candidate -> Organisations -> Questions -> Answer

### CODE REVIEW

**Comment by EdwardBetts** [comment]
Github tells me that I need to use the command line to resolve conflicts to merge this pull request. I'm doing this now.

**Comment by EdwardBetts** [comment]
This change adds a constituency table. Do you have some code for populating the constituency table?

The candidates table contains constituency_id and constituency_name, should we normalise the data? We can join candidates and constituency to get the name of the constituency, then we can remove the constituency_name field from the candidates table.

**Comment by graphiclunarkid** [comment]
I don't have code to populate the constituency table. It will be needed in case someone visits a constituency URL directly before its details have been brought back via a post-code look-up. I also need to make invalid constituency ID URLs return a 404. not a DoesNotExist exception!

We should normalise the data as you suggest. I haven't explored how to do that yet.

I'll raise new issues for the remaining tasks of these so that we don't forget about them. We can continue the discussion on those issues, if necessary, rather than here.

**Comment by graphiclunarkid** [comment]
Oh, my bad, we're not using issues in this repository. I've got a note of them all, though, and will try to work through as many as I can.

**Pull request merged**
